# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Check with isort
        run: poetry run isort sprint_velocity --check-only
      - name: Lint with black
        run: poetry run  black sprint_velocity --check
      - name: Lint with flake8
        run: poetry run flake8 sprint_velocity
      - name: Check if project starts without error
        run: |
          poetry build --format=wheel
          pip install dist/*
          jira_statistics --help
